### ISSUE TITLE
not com.aviary.android.feather.sdk

### ISSUE THREAD

**Issue by empty-user77** [kitek/Aviary-Android-SDK#1]
SDK/src/main/java/com/aviary/android/feather/sdk/panels/EffectsPanel.java
Error:(26, 44) error: cannot find symbol class Generator
Error:(149, 13) error: cannot find symbol class Generator
Error:(157, 43) error: cannot find symbol class Generator
/src/main/java/com/aviary/android/feather/sdk/widget/ImageViewTiltiShiftTouch.java
Error:(27, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(28, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(29, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(30, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(154, 10) error: cannot find symbol class EasingManager
Error:(880, 11) error: cannot find symbol class Easing
/src/main/java/com/aviary/android/feather/sdk/widget/HighlightView.java
Error:(18, 63) error: cannot find symbol class ReflectionException
Error:(22, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(23, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(569, 12) error: cannot find symbol class Easing
/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/AviaryMainController.java
Error:(634, 19) error: cannot find symbol method getApplicationTotalMemory()
/src/main/java/com/aviary/android/feather/sdk/panels/AbstractPanelLoaderService.java
Error:(39, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(40, 80) error: cannot find symbol variable BRIGHTNESS
Error:(43, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(44, 80) error: cannot find symbol variable SATURATION
Error:(47, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(48, 80) error: cannot find symbol variable CONTRAST
Error:(55, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(56, 80) error: cannot find symbol variable WARMTH
Error:(142, 43) error: cannot find symbol variable BRIGHTNESS
Error:(144, 43) error: cannot find symbol variable CONTRAST
Error:(146, 43) error: cannot find symbol variable SATURATION
Error:(148, 43) error: cannot find symbol variable WARMTH
Error:(206, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(208, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(210, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
Error:(234, 9) error: an enum switch case label must be the unqualified name of an enumeration constant
/src/main/java/com/aviary/android/feather/sdk/FeatherActivity.java
Error:(587, 48) error: cannot find symbol method getApplicationTotalMemory()
Error:(1060, 19) error: cannot find symbol method isIceCreamSandwich()
Error:(1415, 25) error: no suitable method found for compareBySize(Bitmap,Bitmap)
method BitmapUtils.compareBySize(Drawable,Drawable) is not applicable
(actual argument Bitmap cannot be converted to Drawable by method invocation conversion)
method BitmapUtils.compareBySize(Drawable,Bitmap) is not applicable
(actual argument Bitmap cannot be converted to Drawable by method invocation conversion)
Error:(1923, 2) error: FeatherActivity.SaveHiResImageTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(1952, 3) error: method does not override or implement a method from a supertype
Error:(1978, 3) error: method does not override or implement a method from a supertype
Error:(2094, 3) error: method does not override or implement a method from a supertype
Error:(2165, 3) error: method does not override or implement a method from a supertype
/src/main/java/com/aviary/android/feather/sdk/FeatherDownloadImageAsyncTask.java
Error:(23, 1) error: FeatherDownloadImageAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(88, 2) error: method does not override or implement a method from a supertype
Error:(135, 2) error: method does not override or implement a method from a supertype
Error:(142, 2) error: method does not override or implement a method from a supertype
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/async_tasks/DownloadImageAsyncTask.java
Error:(20, 8) error: DownloadImageAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(82, 2) error: method does not override or implement a method from a supertype
Error:(113, 2) error: method does not override or implement a method from a supertype
Error:(144, 41) error: cannot find symbol method getApplicationTotalMemory()
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/widget/AdjustImageView.java
Error:(34, 63) error: cannot find symbol class ReflectionException
Error:(38, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(39, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(40, 43) error: package it.sephiroth.android.library.easing does not exist
Error:(102, 10) error: cannot find symbol class Easing
Error:(158, 25) error: cannot find symbol class Easing
Error:(102, 31) error: cannot find symbol class Expo
Error:(211, 13) error: cannot find symbol class ReflectionException
Error:(221, 13) error: cannot find symbol class ReflectionException
Error:(1567, 9) error: cannot find symbol class Linear
Error:(1567, 29) error: cannot find symbol class Linear
Error:(1595, 9) error: cannot find symbol class Linear
Error:(1595, 29) error: cannot find symbol class Linear
Error:(1625, 9) error: cannot find symbol class Linear
Error:(1625, 29) error: cannot find symbol class Linear
Error:(1660, 9) error: cannot find symbol class Linear
Error:(1660, 29) error: cannot find symbol class Linear
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/widget/ImageViewSpotSingleTap.java
Error:(218, 11) error: cannot find symbol variable LOG_TAG
Error:(252, 10) error: cannot find symbol variable LOG_TAG
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/panels/BlemishPanel.java
Error:(459, 2) error: BlemishPanel.GenerateResultTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(463, 3) error: method does not override or implement a method from a supertype
Error:(495, 3) error: method does not override or implement a method from a supertype
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/widget/IAPDialogList.java
Error:(57, 55) error: package com.nhaarman.listviewanimations.swinginadapters does not exist
Error:(58, 64) error: package com.nhaarman.listviewanimations.swinginadapters.prepared does not exist
Error:(104, 10) error: cannot find symbol class AnimationAdapter
Error:(552, 29) error: cannot find symbol class SwingBottomInAnimationAdapter
Error:(160, 60) error: cannot find symbol method getCpuMhz()
Error:(160, 85) error: cannot find symbol variable MHZ_CPU_FAST
Error:(558, 3) error: method does not override or implement a method from a supertype
Error:(788, 2) error: IAPDialogList.QueryInventoryAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(830, 3) error: method does not override or implement a method from a supertype
Error:(922, 3) error: method does not override or implement a method from a supertype
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/widget/IAPDialogMain.java
Error:(569, 32) error: cannot find symbol method createSubscriptionIntent(Context,String,String,String)
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/panels/BordersPanel.java
Error:(67, 44) error: cannot find symbol class Generator
Error:(1128, 13) error: cannot find symbol class Generator
Error:(311, 14) error: cannot find symbol method getRuntimeMemoryInfo(double[])
Error:(328, 35) error: cannot find symbol method getFastPreviewEnabled()
Error:(1030, 4) error: cannot find symbol class Generator
Error:(1052, 21) error: cannot find symbol variable SCHEME_CUSTOM
Error:(1236, 12) error: BordersPanel.RenderTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(1253, 3) error: method does not override or implement a method from a supertype
Error:(1326, 3) error: method does not override or implement a method from a supertype
Error:(1378, 19) error: cannot find symbol method isHoneyComb()
Error:(1413, 2) error: BordersPanel.GenerateResultTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(1417, 3) error: method does not override or implement a method from a supertype
Error:(1440, 3) error: method does not override or implement a method from a supertype
/Users/leeyongbum/Dev/AndroidStudio/TravelKing_Android/Aviary-SDK/src/main/java/com/aviary/android/feather/sdk/widget/IAPDialogDetail.java
Error:(102, 34) error: cannot find symbol method getApplicationTotalMemory()
Error:(718, 2) error: IAPDialogDetail.LoadPreviewsAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(726, 3) error: method does not override or implement a method from a supertype
Error:(744, 3) error: method does not override or implement a method from a supertype
Error:(796, 2) error: IAPDialogDetail.PreviewDownloadAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Error:(824, 3) error: method does not override or implement a method from a supertype
Error:(845, 3) error: method does not override or implement a method from a supertype
Error:(856, 2) error: IAPDialogDetail.DeterminePackOptionAsyncTask is not abstract and does not override abstract method doPreExecute() in AviaryAsyncTask
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /src/main/java/com/aviary/android/feather/sdk/opengl/AviaryGLSurfaceView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Error:Execution failed for task ':Aviary-SDK:compileReleaseJava'.

> Compilation failed; see the compiler error output for details.

help

**Comment by dvidz** [comment]
Since yesterday i have exactly the same issue.

What's wrong? I suppose it's due to an update on maven repo? Please fix. thk

**Comment by empty-user77** [comment]
Resolution.
If you are a gradle build

**Comment by dvidz** [comment]
How do you fix that?

**Comment by empty-user77** [comment]
app/build.gradle

repositories {
    mavenCentral()
    maven {
        name 'maven.aviary.com'
        url uri("http://maven.aviary.com/repo/release")
    }
}
dependencies {
    compile 'com.aviary.android.feather.sdk:aviary-sdk:3.4.3.351'
}

remove Aviary-SDK directory

**Comment by dvidz** [comment]
Thanks for your reply; but I need to compile the SDK in order to make to customize the styles.

**Comment by brunosandoz** [comment]
I have the same issue
